import java.util.ArrayList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.1";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        MainMenu MenuObject = new MainMenu();
        Person person1= new Person("ilya",1999,"kulakov");
        person1.Addperson("vas",1222,"asa");

    }

}

