/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;

import static org.junit.jupiter.api.Assertions.assertEquals;

@Tag("fast")
public class AppTest {

    @Test
    @DisplayName("My 1st JUnit 5 test! 😎")
    public void testAppHasAGreeting() {

        assertEquals("My 1st JUnit 5 test! 😎", "My 1st JUnit 5 test! 😎", () -> "TestInfo is injected correctly");
    }
}
